### ISSUE TITLE
404 error when "display all products" is selected in the products component

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-snipcartshop-plugin#16] opened 2017-06-14 08:27 UTC
Hello,

With the "Display a list of products" component, on the Category filter option, if I choose the "Show all products" option, the system redirect me to the 404 error page.

If I choose one category, it works.

**Comment by tobias-kuendig** [comment] 2017-06-14 12:25
Thanks for your report. This is fixed in version 1.0.25. Make sure to reselect the "show all products" option on the compontent and save your page again. After that the problem is solved.

**Closed by tobias-kuendig** 2017-06-14 12:25 UTC
